apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-mgmt
  template:
    metadata:
      labels:
        app: customer-mgmt
    spec:
      containers:
        - name: customer-mgmt
          image: sela1811/customer-mgmt:v1.0.7
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://root:secretpassword@mongodb-headless.mongodb.svc.cluster.local:27017/mydatabase?authSource=admin"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-0.kafka-cluster-headless.kafka-cluster.svc.cluster.local:9092"