apiVersion: v1
kind: Service
metadata:
  name: customer-mgmt
  namespace: customer-mgmt
spec:
  selector:
    app: customer-mgmt
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
